module

public import Mathlib.Data.Finsupp.Basic
public import Mathlib.Data.Finsupp.Defs
public import Mathlib.Data.List.NodupEquivFin
public import Mathlib.Data.Finset.Max
public import Mathlib.Algebra.BigOperators.Group.Finset.Basic
public import Mathlib.Tactic

/-!
# Finite stochastic choice and random strict rankings

A ranking is a duplicate-free best-to-worst list containing every alternative.
A ranking law is finitely supported, nonnegative, and of total mass one.
No bound on the number of alternatives is imposed.

Authors: Arthur Freitas Ramos, David Barros Hulak,
Ruy Jose Guerra Barretto de Queiroz.
-/

@[expose] public section

namespace Falmagne

variable {X : Type*} [Fintype X] [DecidableEq X]

def IsRanking (l : List X) : Prop :=
  l.Nodup ∧ l.toFinset = Finset.univ

/-- The alternatives weakly below `x` in the best-to-worst list. -/
def lowerContour (l : List X) (x : X) : Finset X :=
  l.toFinset.filter fun y => l.idxOf x ≤ l.idxOf y

/-- Deterministic menu choice; the empty menu has no chosen alternative. -/
noncomputable def rankingChoice (l : List X) (A : Finset X) (x : X) : ℝ :=
  if x ∈ A ∧ A ⊆ lowerContour l x then 1 else 0

abbrev RankingLaw (X : Type*) := List X →₀ ℝ

/-- Probability laws supported on complete strict rankings. -/
def IsRankingLaw (w : RankingLaw X) : Prop :=
  (∀ l, 0 ≤ w l) ∧
  (∀ l ∈ w.support, IsRanking l) ∧
  w.sum (fun _ a => a) = 1

/-- A stochastic choice rule on all menus; the empty menu is zero. -/
def IsChoiceRule (p : Finset X → X → ℝ) : Prop :=
  (∀ A x, 0 ≤ p A x) ∧
  (∀ A x, x ∉ A → p A x = 0) ∧
  (∀ A, A.Nonempty → ∑ x ∈ A, p A x = 1)

/-- All observed menu probabilities are generated by the same ranking law. -/
def Represents (w : RankingLaw X) (p : Finset X → X → ℝ) : Prop :=
  ∀ A x, p A x = w.sum (fun l a => a * rankingChoice l A x)

variable {l : List X} {A : Finset X} {x y : X}

lemma ranking_mem (hl : IsRanking l) (x : X) : x ∈ l := by
  have : x ∈ l.toFinset := by rw [hl.2]; exact Finset.mem_univ x
  simpa using this

@[simp] lemma mem_lowerContour (l : List X) (x y : X) :
    y ∈ lowerContour l x ↔ y ∈ l ∧ l.idxOf x ≤ l.idxOf y := by
  simp [lowerContour]

lemma self_mem_lowerContour (hl : IsRanking l) (x : X) :
    x ∈ lowerContour l x := by
  simp [ranking_mem hl x]

lemma rankingChoice_nonneg (l : List X) (A : Finset X) (x : X) :
    0 ≤ rankingChoice l A x := by
  unfold rankingChoice
  split <;> norm_num

lemma rankingChoice_eq_zero_of_not_mem (hx : x ∉ A) :
    rankingChoice l A x = 0 := by simp [rankingChoice, hx]

lemma rankingChoice_eq_one_iff :
    rankingChoice l A x = 1 ↔ x ∈ A ∧ A ⊆ lowerContour l x := by
  simp [rankingChoice]

lemma rankingChoice_ne_zero_iff :
    rankingChoice l A x ≠ 0 ↔ x ∈ A ∧ A ⊆ lowerContour l x := by
  simp [rankingChoice]

lemma lowerContour_subset_iff (hl : IsRanking l) :
    A ⊆ lowerContour l x ↔ ∀ y ∈ A, l.idxOf x ≤ l.idxOf y := by
  constructor
  · intro h y hy
    exact (mem_lowerContour l x y).mp (h hy) |>.2
  · intro h y hy
    exact (mem_lowerContour l x y).mpr ⟨ranking_mem hl y, h y hy⟩

lemma chosen_unique (hl : IsRanking l)
    (hx : x ∈ A ∧ A ⊆ lowerContour l x)
    (hy : y ∈ A ∧ A ⊆ lowerContour l y) : x = y := by
  have hxy := (mem_lowerContour l x y).mp (hx.2 hy.1) |>.2
  have hyx := (mem_lowerContour l y x).mp (hy.2 hx.1) |>.2
  exact (List.idxOf_inj (ranking_mem hl x)).mp (Nat.le_antisymm hxy hyx)

lemma exists_chosen (hl : IsRanking l) (hA : A.Nonempty) :
    ∃ x ∈ A, A ⊆ lowerContour l x := by
  obtain ⟨x, hx, hmin⟩ := Finset.exists_min_image A (fun x => l.idxOf x) hA
  exact ⟨x, hx, (lowerContour_subset_iff hl).mpr hmin⟩

lemma sum_rankingChoice (hl : IsRanking l) (hA : A.Nonempty) :
    ∑ x ∈ A, rankingChoice l A x = 1 := by
  obtain ⟨x, hx, hchosen⟩ := exists_chosen hl hA
  rw [Finset.sum_eq_single x]
  · simp [rankingChoice, hx, hchosen]
  · intro y hy hyx
    by_cases h : y ∈ A ∧ A ⊆ lowerContour l y
    · exact (hyx (chosen_unique hl h ⟨hx, hchosen⟩)).elim
    · simp [rankingChoice, h]
  · intro h
    exact (h hx).elim

end Falmagne
