module

public import EconomicsNextProof.Conservation
public import EconomicsNextProof.Representation
public import EconomicsNextProof.Falmagne

/-! Exact finite adversarial regression examples. -/
@[expose] public section

namespace Falmagne.Examples
open Finset EconomicsNextProof

/-- A regular four-alternative choice rule that fails a higher-order BM inequality. -/
def regularCounterexampleQ (A : Finset (Fin 4)) (x : Fin 4) : ℚ :=
  if x ∉ A then 0 else
    if (0 : Fin 4) ∈ A ∧ 3 ≤ A.card then
      if x = 0 then 0 else 1 / ((A.card - 1 : ℕ) : ℚ)
    else 1 / (A.card : ℚ)

noncomputable def regularCounterexample (A : Finset (Fin 4)) (x : Fin 4) : ℝ :=
  regularCounterexampleQ A x

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
lemma regularCounterexampleQ_normalized :
    (∀ A x, 0 ≤ regularCounterexampleQ A x) ∧
    (∀ A x, x ∉ A → regularCounterexampleQ A x = 0) ∧
    (∀ A, A.Nonempty → ∑ x ∈ A, regularCounterexampleQ A x = 1) := by
  decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
lemma regularCounterexampleQ_regular :
    ∀ A B : Finset (Fin 4), A ⊆ B →
      ∀ x ∈ A, regularCounterexampleQ B x ≤ regularCounterexampleQ A x := by
  decide +kernel

lemma regularCounterexample_isChoiceRule : IsChoiceRule regularCounterexample := by
  obtain ⟨hnonneg, hoff, hnorm⟩ := regularCounterexampleQ_normalized
  refine ⟨?_, ?_, ?_⟩
  · intro A x
    unfold regularCounterexample
    exact_mod_cast hnonneg A x
  · intro A x hx
    unfold regularCounterexample
    exact_mod_cast hoff A x hx
  · intro A hA
    unfold regularCounterexample
    exact_mod_cast hnorm A hA

lemma regularCounterexample_regular :
    ∀ A B : Finset (Fin 4), A ⊆ B →
      ∀ x ∈ A, regularCounterexample B x ≤ regularCounterexample A x := by
  intro A B hAB x hx
  unfold regularCounterexample
  exact_mod_cast regularCounterexampleQ_regular A B hAB x hx

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
lemma regularCounterexampleQ_bm :
    (∑ B ∈ univ.filter (fun B : Finset (Fin 4) => {(0 : Fin 4)} ⊆ B),
      (-1 : ℚ) ^ (B \ {(0 : Fin 4)}).card * regularCounterexampleQ B 0) = -1 / 2 := by
  decide +kernel

lemma regularCounterexample_bm :
    blockMarschak regularCounterexample (0 : Fin 4) {0} = -1 / 2 := by
  unfold blockMarschak upperMobius regularCounterexample
  have h := congrArg (fun q : ℚ => (q : ℝ)) regularCounterexampleQ_bm
  push_cast at h
  exact h

lemma regularCounterexample_bm_negative :
    blockMarschak regularCounterexample (0 : Fin 4) {0} < 0 := by
  rw [regularCounterexample_bm]
  norm_num

/-- The counterexample cannot be generated by any random strict ranking. -/
lemma regularCounterexample_not_representable :
    ¬ ∃ w : RankingLaw (Fin 4), IsRankingLaw w ∧ Represents w regularCounterexample := by
  rintro ⟨w, hw, hp⟩
  have h := blockMarschak_necessary hw hp (0 : Fin 4) {0} (by simp)
  change 0 ≤ blockMarschak regularCounterexample (0 : Fin 4) {0} at h
  linarith [regularCounterexample_bm_negative]

def singletonRanking : List (Fin 1) := [0]
noncomputable def singletonLaw : RankingLaw (Fin 1) := Finsupp.single singletonRanking 1

lemma singletonRanking_isRanking : IsRanking singletonRanking := by
  constructor <;> decide +kernel

lemma singletonLaw_isRankingLaw : IsRankingLaw singletonLaw := by
  refine ⟨?_, ?_, ?_⟩
  · intro l
    simp only [singletonLaw, Finsupp.single_apply]
    split_ifs <;> norm_num
  · intro l hl
    by_cases h : l = singletonRanking
    · subst l
      exact singletonRanking_isRanking
    · simp [singletonLaw, h] at hl
  · simp [singletonLaw]

lemma singletonLaw_represents :
    Represents singletonLaw (rankingChoice singletonRanking) := by
  intro A x
  simp [singletonLaw]

lemma singleton_isChoiceRule : IsChoiceRule (rankingChoice singletonRanking) :=
  represented_isChoiceRule singletonLaw_isRankingLaw singletonLaw_represents

lemma singleton_probability_one :
    rankingChoice singletonRanking {(0 : Fin 1)} 0 = 1 := by
  norm_num [rankingChoice, lowerContour, singletonRanking]

lemma singleton_empty_menu_zero :
    rankingChoice singletonRanking ∅ (0 : Fin 1) = 0 := by
  simp [rankingChoice]

def forwardRanking : List (Fin 4) := [0, 1, 2, 3]
def reverseRanking : List (Fin 4) := [3, 2, 1, 0]

lemma forwardRanking_isRanking : IsRanking forwardRanking := by
  constructor <;> decide +kernel
lemma reverseRanking_isRanking : IsRanking reverseRanking := by
  constructor <;> decide +kernel

noncomputable def mixtureLaw : RankingLaw (Fin 4) :=
  Finsupp.single forwardRanking (1 / 2) + Finsupp.single reverseRanking (1 / 2)

noncomputable def mixtureChoice (A : Finset (Fin 4)) (x : Fin 4) : ℝ :=
  (1 / 2) * rankingChoice forwardRanking A x +
  (1 / 2) * rankingChoice reverseRanking A x

lemma mixtureLaw_isRankingLaw : IsRankingLaw mixtureLaw := by
  refine ⟨?_, ?_, ?_⟩
  · intro l
    simp only [mixtureLaw, Finsupp.add_apply, Finsupp.single_apply]
    split_ifs <;> norm_num
  · intro l hl
    by_cases hf : l = forwardRanking
    · subst l
      exact forwardRanking_isRanking
    by_cases hr : l = reverseRanking
    · subst l
      exact reverseRanking_isRanking
    simp [mixtureLaw, Finsupp.mem_support_iff, hf, hr] at hl
  · simp [mixtureLaw, Finsupp.sum_add_index]
    norm_num

lemma mixtureLaw_represents : Represents mixtureLaw mixtureChoice := by
  intro A x
  simp [mixtureChoice, mixtureLaw, Finsupp.sum_add_index, add_mul]

lemma mixture_isChoiceRule : IsChoiceRule mixtureChoice :=
  represented_isChoiceRule mixtureLaw_isRankingLaw mixtureLaw_represents

lemma mixture_full_menu_endpoint_probability :
    mixtureChoice univ (0 : Fin 4) = 1 / 2 := by
  have hf : (0 : Fin 4) ∈ univ ∧ univ ⊆ lowerContour forwardRanking 0 := by
    decide +kernel
  have hr : ¬ ((0 : Fin 4) ∈ univ ∧ univ ⊆ lowerContour reverseRanking 0) := by
    decide +kernel
  simp only [mixtureChoice, rankingChoice, ite_eq_left hf, ite_eq_right hr]
  norm_num

lemma mixture_full_menu_middle_probability_zero :
    mixtureChoice univ (1 : Fin 4) = 0 := by
  have hf : ¬ ((1 : Fin 4) ∈ univ ∧ univ ⊆ lowerContour forwardRanking 1) := by
    decide +kernel
  have hr : ¬ ((1 : Fin 4) ∈ univ ∧ univ ⊆ lowerContour reverseRanking 1) := by
    decide +kernel
  simp only [mixtureChoice, rankingChoice, ite_eq_right hf, ite_eq_right hr]
  norm_num

lemma mixture_BM_nonnegative :
    ∀ x A, x ∈ A → 0 ≤ blockMarschak mixtureChoice x A := by
  exact blockMarschak_necessary mixtureLaw_isRankingLaw mixtureLaw_represents

lemma singleton_BM_empty_negative :
    blockMarschak (rankingChoice singletonRanking) (0 : Fin 1) ∅ = -1 := by
  rw [blockMarschak_not_mem _ singleton_isChoiceRule ∅ 0 (by simp)]
  have hu : ({0} : Finset (Fin 1)) = univ := by decide +kernel
  simp only [insert_empty_eq, hu, blockMarschak_univ]
  have hp : rankingChoice singletonRanking (univ : Finset (Fin 1)) 0 = 1 := by
    rw [← hu]
    exact singleton_probability_one
  rw [hp]

/-- A positive singleton case also instantiates the completed characterization. -/
lemma singleton_falmagne :
    RandomUtilityRepresentable (rankingChoice singletonRanking) ↔
      BlockMarschakNonnegative (rankingChoice singletonRanking) :=
  falmagne_blockMarschak singleton_isChoiceRule

/-- Sparse choice probabilities, including exact zeros, satisfy the completed theorem. -/
lemma mixture_falmagne :
    RandomUtilityRepresentable mixtureChoice ↔ BlockMarschakNonnegative mixtureChoice :=
  falmagne_blockMarschak mixture_isChoiceRule

lemma regularity_is_not_sufficient :
    IsChoiceRule regularCounterexample ∧
    (∀ A B : Finset (Fin 4), A ⊆ B → ∀ x ∈ A,
      regularCounterexample B x ≤ regularCounterexample A x) ∧
    ¬ RandomUtilityRepresentable regularCounterexample :=
  ⟨regularCounterexample_isChoiceRule, regularCounterexample_regular,
    regularCounterexample_not_representable⟩

lemma mixture_zero_BM_edge : blockMarschak mixtureChoice (1 : Fin 4) univ = 0 := by
  rw [blockMarschak_univ]
  exact mixture_full_menu_middle_probability_zero

lemma mixture_unit_flow : IsFlow (blockMarschak mixtureChoice) 1 :=
  blockMarschak_isFlow mixtureChoice mixture_isChoiceRule mixture_BM_nonnegative

lemma deterministic_forward_isChoiceRule : IsChoiceRule (rankingChoice forwardRanking) := by
  refine ⟨rankingChoice_nonneg forwardRanking, ?_, ?_⟩
  · intro A x hx
    exact rankingChoice_eq_zero_of_not_mem hx
  · intro A hA
    exact sum_rankingChoice forwardRanking_isRanking hA

lemma deterministic_forward_choice_one :
    rankingChoice forwardRanking univ (0 : Fin 4) = 1 := by
  apply rankingChoice_eq_one_iff.mpr
  decide +kernel

lemma deterministic_forward_zero_branch :
    rankingChoice forwardRanking univ (1 : Fin 4) = 0 := by
  have h : ¬ ((1 : Fin 4) ∈ univ ∧ univ ⊆ lowerContour forwardRanking 1) := by
    decide +kernel
  simp only [rankingChoice, ite_eq_right h]

end Falmagne.Examples
