/-
Falmagne–Block–Marschak characterization.
Authors: Arthur Freitas Ramos, David Barros Hulak,
Ruy Jose Guerra Barretto de Queiroz.
Released under Apache 2.0.
-/
module
public import Mathlib.Data.Finsupp.Basic
public import Mathlib.Data.Finsupp.Defs
public import Mathlib.Data.List.NodupEquivFin
public import Mathlib.Data.Finset.Max
public import Mathlib.Algebra.BigOperators.Group.Finset.Basic
public import Mathlib.Basic.Real.Basic
public import Mathlib.Data.Finset.Interval
public import Mathlib.Data.Nat.Choose.Sum
public import Mathlib.Combinatorics.Enumerative.IncidenceAlgebra
public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import Mathlib.Tactic

@[expose] public section


/-! ## Basic -/


/-!
# Finite stochastic choice and random strict rankings

A ranking is a duplicate-free best-to-worst list containing every alternative.
A ranking law is finitely supported, nonnegative, and of total mass one.
No bound on the number of alternatives is imposed.

Authors: Arthur Freitas Ramos, David Barros Hulak,
Ruy Jose Guerra Barretto de Queiroz.
-/


namespace Falmagne

variable {X : Type*} [Fintype X] [DecidableEq X]

def IsRanking (l : List X) : Prop :=
  l.Nodup ∧ l.toFinset = Finset.univ

/-- The alternatives weakly below `x` in the best-to-worst list. -/
def lowerContour (l : List X) (x : X) : Finset X :=
  l.toFinset.filter fun y => l.idxOf x ≤ l.idxOf y

/-- Deterministic menu choice; the empty menu has no chosen alternative. -/
noncomputable def rankingChoice (l : List X) (A : Finset X) (x : X) : ℝ :=
  if x ∈ A ∧ A ⊆ lowerContour l x then 1 else 0

abbrev RankingLaw (X : Type*) := List X →₀ ℝ

/-- Probability laws supported on complete strict rankings. -/
def IsRankingLaw (w : RankingLaw X) : Prop :=
  (∀ l, 0 ≤ w l) ∧
  (∀ l ∈ w.support, IsRanking l) ∧
  w.sum (fun _ a => a) = 1

/-- A stochastic choice rule on all menus; the empty menu is zero. -/
def IsChoiceRule (p : Finset X → X → ℝ) : Prop :=
  (∀ A x, 0 ≤ p A x) ∧
  (∀ A x, x ∉ A → p A x = 0) ∧
  (∀ A, A.Nonempty → ∑ x ∈ A, p A x = 1)

/-- All observed menu probabilities are generated by the same ranking law. -/
def Represents (w : RankingLaw X) (p : Finset X → X → ℝ) : Prop :=
  ∀ A x, p A x = w.sum (fun l a => a * rankingChoice l A x)

variable {l : List X} {A : Finset X} {x y : X}

lemma ranking_mem (hl : IsRanking l) (x : X) : x ∈ l := by
  have : x ∈ l.toFinset := by rw [hl.2]; exact Finset.mem_univ x
  simpa using this

@[simp] lemma mem_lowerContour (l : List X) (x y : X) :
    y ∈ lowerContour l x ↔ y ∈ l ∧ l.idxOf x ≤ l.idxOf y := by
  simp [lowerContour]

lemma self_mem_lowerContour (hl : IsRanking l) (x : X) :
    x ∈ lowerContour l x := by
  simp [ranking_mem hl x]

lemma rankingChoice_nonneg (l : List X) (A : Finset X) (x : X) :
    0 ≤ rankingChoice l A x := by
  unfold rankingChoice
  split <;> norm_num

lemma rankingChoice_eq_zero_of_not_mem (hx : x ∉ A) :
    rankingChoice l A x = 0 := by simp [rankingChoice, hx]

lemma rankingChoice_eq_one_iff :
    rankingChoice l A x = 1 ↔ x ∈ A ∧ A ⊆ lowerContour l x := by
  simp [rankingChoice]

lemma rankingChoice_ne_zero_iff :
    rankingChoice l A x ≠ 0 ↔ x ∈ A ∧ A ⊆ lowerContour l x := by
  simp [rankingChoice]

lemma lowerContour_subset_iff (hl : IsRanking l) :
    A ⊆ lowerContour l x ↔ ∀ y ∈ A, l.idxOf x ≤ l.idxOf y := by
  constructor
  · intro h y hy
    exact (mem_lowerContour l x y).mp (h hy) |>.2
  · intro h y hy
    exact (mem_lowerContour l x y).mpr ⟨ranking_mem hl y, h y hy⟩

lemma chosen_unique (hl : IsRanking l)
    (hx : x ∈ A ∧ A ⊆ lowerContour l x)
    (hy : y ∈ A ∧ A ⊆ lowerContour l y) : x = y := by
  have hxy := (mem_lowerContour l x y).mp (hx.2 hy.1) |>.2
  have hyx := (mem_lowerContour l y x).mp (hy.2 hx.1) |>.2
  exact (List.idxOf_inj (ranking_mem hl x)).mp (Nat.le_antisymm hxy hyx)

lemma exists_chosen (hl : IsRanking l) (hA : A.Nonempty) :
    ∃ x ∈ A, A ⊆ lowerContour l x := by
  obtain ⟨x, hx, hmin⟩ := Finset.exists_min_image A (fun x => l.idxOf x) hA
  exact ⟨x, hx, (lowerContour_subset_iff hl).mpr hmin⟩

lemma sum_rankingChoice (hl : IsRanking l) (hA : A.Nonempty) :
    ∑ x ∈ A, rankingChoice l A x = 1 := by
  obtain ⟨x, hx, hchosen⟩ := exists_chosen hl hA
  rw [Finset.sum_eq_single x]
  · simp [rankingChoice, hx, hchosen]
  · intro y hy hyx
    by_cases h : y ∈ A ∧ A ⊆ lowerContour l y
    · exact (hyx (chosen_unique hl h ⟨hx, hchosen⟩)).elim
    · simp [rankingChoice, h]
  · intro h
    exact (h hx).elim

end Falmagne

/-! ## Mobius -/


/-! Boolean upper Möbius inversion, for arbitrary finite ground sets. -/

namespace EconomicsNextProof
open Finset
variable {X : Type*} [Fintype X] [DecidableEq X]

noncomputable def upperSum (f : Finset X → ℝ) (A : Finset X) : ℝ :=
  ∑ B ∈ Finset.univ.filter (fun B : Finset X => A ⊆ B), f B

noncomputable def upperMobius (f : Finset X → ℝ) (A : Finset X) : ℝ :=
  ∑ B ∈ Finset.univ.filter (fun B : Finset X => A ⊆ B),
    (-1 : ℝ) ^ (B \ A).card * f B

omit [Fintype X] in
private lemma alternating_powerset (s : Finset X) :
    (∑ D ∈ s.powerset, (-1 : ℝ) ^ D.card) = if s = ∅ then 1 else 0 := by
  exact_mod_cast (Finset.sum_powerset_neg_one_pow_card (x := s))

lemma alternating_interval (A C : Finset X) (hAC : A ⊆ C) :
    (∑ B ∈ Finset.Icc A C, (-1 : ℝ) ^ (B \ A).card) = if A = C then 1 else 0 := by
  rw [Finset.Icc_eq_image_powerset hAC, Finset.sum_image]
  · have h : ∀ D ∈ (C \ A).powerset, (A ∪ D) \ A = D := by
      intro D hD
      have hDA := Finset.mem_powerset.mp hD
      ext x
      simp only [Finset.mem_sdiff, Finset.mem_union]
      constructor
      · tauto
      · intro hx
        exact ⟨Or.inr hx, (Finset.mem_sdiff.mp (hDA hx)).2⟩
    calc
      ∑ D ∈ (C \ A).powerset, (-1 : ℝ) ^ ((A ∪ D) \ A).card
          = ∑ D ∈ (C \ A).powerset, (-1 : ℝ) ^ D.card := by
              exact Finset.sum_congr rfl (fun D hD => by rw [h D hD])
      _ = if A = C then 1 else 0 := by
        rw [alternating_powerset]
        congr 1
        exact propext ⟨fun h => Finset.Subset.antisymm hAC
          (Finset.sdiff_eq_empty_iff_subset.mp h), fun h => by simp [h]⟩

  · intro D hD E hE hEq
    have hDA := Finset.mem_powerset.mp hD
    have hEA := Finset.mem_powerset.mp hE
    ext x
    have hdx : x ∈ D → x ∉ A := fun hx => (Finset.mem_sdiff.mp (hDA hx)).2
    have hex : x ∈ E → x ∉ A := fun hx => (Finset.mem_sdiff.mp (hEA hx)).2
    have heq := Finset.ext_iff.mp hEq x
    simp only [Finset.mem_union] at heq
    tauto

private noncomputable def booleanMu : IncidenceAlgebra ℝ (Finset X) where
  toFun A B := if A ⊆ B then (-1 : ℝ) ^ (B \ A).card else 0
  eq_zero_of_not_le' := by intros; simp_all

private lemma booleanMu_eq_mu :
    (booleanMu : IncidenceAlgebra ℝ (Finset X)) = IncidenceAlgebra.mu ℝ := by
  have h : (booleanMu : IncidenceAlgebra ℝ (Finset X)) *
      IncidenceAlgebra.zeta ℝ = 1 := by
    apply IncidenceAlgebra.ext
    intro A C hAC
    rw [IncidenceAlgebra.mul_apply]
    calc
      ∑ B ∈ Finset.Icc A C, booleanMu A B * IncidenceAlgebra.zeta ℝ B C
          = ∑ B ∈ Finset.Icc A C, (-1 : ℝ) ^ (B \ A).card := by
              apply Finset.sum_congr rfl
              intro B hB
              have hb := Finset.mem_Icc.mp hB
              simp [booleanMu, IncidenceAlgebra.zeta_apply, hb.1, hb.2]
      _ = (1 : IncidenceAlgebra ℝ (Finset X)) A C := by
        rw [alternating_interval A C hAC, IncidenceAlgebra.one_apply]
  calc
    booleanMu = booleanMu * (IncidenceAlgebra.zeta ℝ * IncidenceAlgebra.mu ℝ) := by
      rw [IncidenceAlgebra.zeta_mul_mu, mul_one]
    _ = (booleanMu * IncidenceAlgebra.zeta ℝ) * IncidenceAlgebra.mu ℝ := by rw [mul_assoc]
    _ = IncidenceAlgebra.mu ℝ := by rw [h, one_mul]

private lemma upperSum_eq_Ici (f : Finset X → ℝ) (A : Finset X) :
    upperSum f A = ∑ B ∈ Finset.Ici A, f B := by
  unfold upperSum
  congr 1
  ext B
  simp

private lemma upperMobius_eq_mu (f : Finset X → ℝ) (A : Finset X) :
    upperMobius f A = ∑ B ∈ Finset.Ici A, IncidenceAlgebra.mu ℝ A B * f B := by
  have hs : Finset.univ.filter (fun B : Finset X => A ⊆ B) = Finset.Ici A := by
    ext B
    simp
  rw [upperMobius, hs]
  apply Finset.sum_congr rfl
  intro B hB
  rw [← booleanMu_eq_mu]
  simp [booleanMu, Finset.mem_Ici.mp hB]

/-- Möbius inversion of the upper subset sum on the Boolean lattice. -/
theorem upperMobius_upperSum (f : Finset X → ℝ) : upperMobius (upperSum f) = f := by
  funext A
  rw [upperMobius_eq_mu]
  exact (IncidenceAlgebra.moebius_inversion_top f (upperSum f)
    (fun B => upperSum_eq_Ici f B) A).symm

private noncomputable def upperSumLinear :
    (Finset X → ℝ) →ₗ[ℝ] (Finset X → ℝ) where
  toFun := upperSum
  map_add' f g := by
    funext A
    simp [upperSum, Finset.sum_add_distrib]
  map_smul' r f := by
    funext A
    simp [upperSum, Finset.mul_sum]

/-- The upper subset sum and its Möbius transform are two-sided inverses. -/
theorem upperSum_upperMobius (f : Finset X → ℝ) : upperSum (upperMobius f) = f := by
  have hinj : Function.Injective (upperSumLinear (X := X)) := by
    intro f g hfg
    have h := congrArg upperMobius hfg
    simpa only [upperSumLinear, LinearMap.coe_mk, AddHom.coe_mk,
      upperMobius_upperSum] using h
  have hsurj := (LinearMap.injective_iff_surjective.mp hinj)
  obtain ⟨g, hg⟩ := hsurj f
  change upperSum g = f at hg
  rw [← hg, upperMobius_upperSum]

/-- A constant upper Möbius transform is supported only at the full set. -/
theorem upperMobius_const (c : ℝ) (A : Finset X) :
    upperMobius (fun _ => c) A = if A = Finset.univ then c else 0 := by
  have hs : Finset.univ.filter (fun B : Finset X => A ⊆ B) =
      Finset.Icc A Finset.univ := by
    ext B
    simp
  rw [upperMobius, hs, ← Finset.sum_mul,
    alternating_interval A Finset.univ (Finset.subset_univ A)]
  split_ifs <;> simp

end EconomicsNextProof




/-! ## Representation -/



namespace Falmagne

variable {X : Type*} [Fintype X] [DecidableEq X]
variable {l : List X} {A : Finset X} {x : X}

/-- Unit flow through the lower-contour edge of a strict ranking. -/
noncomputable def rankingEdge (l : List X) (x : X) (A : Finset X) : ℝ :=
  if x ∈ A ∧ A = lowerContour l x then 1 else 0

lemma rankingEdge_nonneg (l : List X) (x : X) (A : Finset X) :
    0 ≤ rankingEdge l x A := by
  unfold rankingEdge
  split <;> norm_num

@[simp] lemma rankingEdge_eq_zero_of_not_mem (hx : x ∉ A) :
    rankingEdge l x A = 0 := by simp [rankingEdge, hx]

/-- Marginal lower-contour flow of a finitely supported ranking law. -/
noncomputable def lawFlow (w : RankingLaw X) (x : X) (A : Finset X) : ℝ :=
  w.sum (fun l a => a * rankingEdge l x A)

lemma lawFlow_nonneg {w : RankingLaw X} (hw : ∀ l, 0 ≤ w l) (x : X) (A : Finset X) :
    0 ≤ lawFlow w x A := by
  unfold lawFlow Finsupp.sum
  exact Finset.sum_nonneg fun l _ => mul_nonneg (hw l) (rankingEdge_nonneg l x A)

lemma lawFlow_off_menu (w : RankingLaw X) (hx : x ∉ A) :
    lawFlow w x A = 0 := by
  simp [lawFlow, rankingEdge, hx]

/-- A ranking law always generates a normalized stochastic choice rule. -/
lemma represented_isChoiceRule {w : RankingLaw X} {p : Finset X → X → ℝ}
    (hw : IsRankingLaw w) (hp : Represents w p) : IsChoiceRule p := by
  unfold Represents at hp
  refine ⟨?_, ?_, ?_⟩
  · intro A x
    rw [hp A x]
    exact Finset.sum_nonneg fun l _ => mul_nonneg (hw.1 l) (rankingChoice_nonneg l A x)
  · intro A x hx
    rw [hp A x]
    simp [rankingChoice, hx]
  · intro A hA
    simp_rw [hp]
    unfold Finsupp.sum
    rw [Finset.sum_comm]
    calc
      _ = ∑ l ∈ w.support, w l * (∑ x ∈ A, rankingChoice l A x) := by
        apply Finset.sum_congr rfl
        intro l hl
        rw [Finset.mul_sum]
      _ = ∑ l ∈ w.support, w l := by
        apply Finset.sum_congr rfl
        intro l hl
        rw [sum_rankingChoice (hw.2.1 l hl) hA, mul_one]
      _ = 1 := hw.2.2

end Falmagne

/-! ## Path -/



namespace Falmagne
variable {X : Type*} [Fintype X] [DecidableEq X]

noncomputable def outflow (q : X → Finset X → ℝ) (A : Finset X) : ℝ :=
  ∑ x ∈ A, q x A
noncomputable def inflow (q : X → Finset X → ℝ) (A : Finset X) : ℝ :=
  ∑ y ∈ Finset.univ \ A, q y (insert y A)

structure IsFlow (q : X → Finset X → ℝ) (m : ℝ) : Prop where
  nonneg : ∀ x A, x ∈ A → 0 ≤ q x A
  source : outflow q Finset.univ = m
  conserve : ∀ A, A.Nonempty → A ≠ Finset.univ → outflow q A = inflow q A

noncomputable def unitEdge (y : X) (B : Finset X) (x : X) (A : Finset X) : ℝ :=
  if x = y ∧ A = B then 1 else 0

noncomputable def pathFlow : List X → X → Finset X → ℝ
  | [], _, _ => 0
  | y :: l, x, A => unitEdge y (y :: l).toFinset x A + pathFlow l x A

@[simp] lemma pathFlow_nil (x : X) (A : Finset X) : pathFlow [] x A = 0 := rfl
@[simp] lemma pathFlow_cons (y : X) (l : List X) (x : X) (A : Finset X) :
    pathFlow (y :: l) x A = unitEdge y (y :: l).toFinset x A + pathFlow l x A := rfl

lemma outflow_add (q r : X → Finset X → ℝ) (A : Finset X) :
    outflow (fun x B => q x B + r x B) A = outflow q A + outflow r A := by
  simp [outflow, Finset.sum_add_distrib]
lemma inflow_add (q r : X → Finset X → ℝ) (A : Finset X) :
    inflow (fun x B => q x B + r x B) A = inflow q A + inflow r A := by
  simp [inflow, Finset.sum_add_distrib]
lemma outflow_sub (q r : X → Finset X → ℝ) (A : Finset X) :
    outflow (fun x B => q x B - r x B) A = outflow q A - outflow r A := by
  simp [outflow, Finset.sum_sub_distrib]
lemma inflow_sub (q r : X → Finset X → ℝ) (A : Finset X) :
    inflow (fun x B => q x B - r x B) A = inflow q A - inflow r A := by
  simp [inflow, Finset.sum_sub_distrib]
lemma outflow_mul (a : ℝ) (q : X → Finset X → ℝ) (A : Finset X) :
    outflow (fun x B => a * q x B) A = a * outflow q A := by
  simp [outflow, Finset.mul_sum]
lemma inflow_mul (a : ℝ) (q : X → Finset X → ℝ) (A : Finset X) :
    inflow (fun x B => a * q x B) A = a * inflow q A := by
  unfold inflow
  rw [Finset.mul_sum]

lemma outflow_unitEdge (hy : y ∈ B) (A : Finset X) :
    outflow (unitEdge y B) A = if A = B then 1 else 0 := by
  classical
  by_cases h : A = B
  · subst A
    simp [outflow, unitEdge, hy]
  · simp [outflow, unitEdge, h]

lemma inflow_unitEdge (hy : y ∈ B) (A : Finset X) :
    inflow (unitEdge y B) A = if A = B.erase y then 1 else 0 := by
  classical
  by_cases h : A = B.erase y
  · subst A
    have hy' : y ∈ Finset.univ \ B.erase y := by simp
    have hi : insert y (B.erase y) = B := Finset.insert_erase hy
    unfold inflow
    rw [Finset.sum_eq_single y]
    · simp [unitEdge, hi]
    · intro z hz hzy
      simp [unitEdge, hzy]
    · intro hy0
      exact (hy0 hy').elim
  · have hzero : ∀ z ∈ Finset.univ \ A, unitEdge y B z (insert z A) = 0 := by
      intro z hz
      simp only [Finset.mem_sdiff, Finset.mem_univ, true_and] at hz
      unfold unitEdge
      split_ifs with heq
      · have hz' : z = y := heq.1
        subst z
        have : A = B.erase y := by rw [← heq.2]; simp [hz]
        exact (h this).elim
      · rfl
    simp [inflow, Finset.sum_eq_zero hzero, h]

lemma pathFlow_nonneg (l : List X) (x : X) (A : Finset X) :
    0 ≤ pathFlow l x A := by
  induction l with
  | nil => simp
  | cons y l ih =>
      rw [pathFlow_cons]
      have h : 0 ≤ unitEdge y (y :: l).toFinset x A := by unfold unitEdge; split <;> norm_num
      exact add_nonneg h ih

lemma pathFlow_zero_of_not_mem (l : List X) (hx : x ∉ l) (A : Finset X) :
    pathFlow l x A = 0 := by
  induction l with
  | nil => simp
  | cons y l ih =>
      simp only [List.mem_cons, not_or] at hx
      simp [pathFlow_cons, unitEdge, hx.1, ih hx.2]

lemma pathFlow_eq_zero_or_one (l : List X) (hl : l.Nodup) (x : X) (A : Finset X) :
    pathFlow l x A = 0 ∨ pathFlow l x A = 1 := by
  induction l with
  | nil => simp
  | cons y l ih =>
      obtain ⟨hyn, hln⟩ := List.nodup_cons.mp hl
      by_cases hxy : x = y
      · subst x
        rw [pathFlow_cons, pathFlow_zero_of_not_mem l hyn]
        unfold unitEdge
        split_ifs <;> simp
      · simpa [pathFlow_cons, unitEdge, hxy] using ih hln

lemma pathFlow_head (y : X) (l : List X) (hyn : y ∉ l) :
    pathFlow (y :: l) y (y :: l).toFinset = 1 := by
  simp [pathFlow_cons, unitEdge, pathFlow_zero_of_not_mem l hyn]

lemma pathFlow_nonzero_mem (l : List X) (hp : pathFlow l x A ≠ 0) : x ∈ A := by
  induction l with
  | nil => simp at hp
  | cons y l ih =>
      by_cases hu : unitEdge y (y :: l).toFinset x A = 0
      · rw [pathFlow_cons, hu, zero_add] at hp
        exact ih hp
      · have heq : x = y ∧ A = (y :: l).toFinset := by simpa [unitEdge] using hu
        rcases heq with ⟨rfl, rfl⟩
        simp

/-- Divergence of the unit path of a duplicate-free list. -/
lemma pathFlow_divergence (l : List X) (hl : l.Nodup) (A : Finset X) :
    outflow (pathFlow l) A - inflow (pathFlow l) A =
      (if A = l.toFinset then 1 else 0) - (if A = ∅ then 1 else 0) := by
  induction l with
  | nil => simp only [outflow, inflow, pathFlow, Finset.sum_const_zero, List.toFinset_nil]; split_ifs <;> simp_all
  | cons y l ih =>
      have hyn : y ∉ l := (List.nodup_cons.mp hl).1
      have hln : l.Nodup := (List.nodup_cons.mp hl).2
      have hy : y ∈ (y :: l).toFinset := by simp
      have herase : (y :: l).toFinset.erase y = l.toFinset := by simp [hyn]
      change outflow (fun x B => unitEdge y (y :: l).toFinset x B + pathFlow l x B) A -
        inflow (fun x B => unitEdge y (y :: l).toFinset x B + pathFlow l x B) A = _
      rw [outflow_add, inflow_add, outflow_unitEdge hy, inflow_unitEdge hy, herase]
      have hi := ih hln
      linarith

lemma pathFlow_source (l : List X) (hl : l.Nodup) (hfull : l.toFinset = Finset.univ)
    [Nonempty X] : outflow (pathFlow l) Finset.univ = 1 := by
  have h := pathFlow_divergence l hl Finset.univ
  have hn : (Finset.univ : Finset X) ≠ ∅ := Finset.univ_nonempty.ne_empty
  simpa [inflow, hfull, hn] using h

lemma pathFlow_conserve (l : List X) (hl : l.Nodup) (hfull : l.toFinset = Finset.univ)
    (A : Finset X) (hA : A.Nonempty) (hU : A ≠ Finset.univ) :
    outflow (pathFlow l) A = inflow (pathFlow l) A := by
  have h := pathFlow_divergence l hl A
  have hz : outflow (pathFlow l) A - inflow (pathFlow l) A = 0 := by
    simpa [hfull, hU, hA.ne_empty] using h
  exact sub_eq_zero.mp hz

end Falmagne

/-! ## Flow -/



namespace Falmagne
variable {X : Type*} [Fintype X] [DecidableEq X]
variable {q : X → Finset X → ℝ} {m : ℝ} {x : X} {A : Finset X}

lemma flow_outflow_nonneg (h : IsFlow q m) (A : Finset X) : 0 ≤ outflow q A := by
  exact Finset.sum_nonneg fun x hx => h.nonneg x A hx

lemma flow_edge_le_outflow (h : IsFlow q m) (hx : x ∈ A) : q x A ≤ outflow q A := by
  exact Finset.single_le_sum (fun y hy => h.nonneg y A hy) hx

lemma flow_inflow_nonneg (h : IsFlow q m) (A : Finset X) : 0 ≤ inflow q A := by
  apply Finset.sum_nonneg
  intro y hy
  exact h.nonneg y (insert y A) (Finset.mem_insert_self _ _)

lemma flow_zero_of_source_zero (h : IsFlow q 0) : ∀ A x, x ∈ A → q x A = 0 := by
  intro A
  induction hn : (Finset.univ \ A).card using Nat.strong_induction_on generalizing A with
  | h n ih =>
      intro x hx
      by_cases hU : A = Finset.univ
      · subst A
        have he := flow_edge_le_outflow h hx
        have hz := h.source
        have hnn := h.nonneg x Finset.univ hx
        linarith
      · have hA : A.Nonempty := ⟨x, hx⟩
        have hi : inflow q A = 0 := by
          unfold inflow
          apply Finset.sum_eq_zero
          intro y hy
          have hyA : y ∉ A := (Finset.mem_sdiff.mp hy).2
          have hlt : (Finset.univ \ insert y A).card < n := by
            rw [← hn]
            apply Finset.card_lt_card
            constructor
            · intro z hz
              simp only [Finset.mem_sdiff, Finset.mem_univ, true_and, Finset.mem_insert,
                not_or] at hz ⊢
              exact hz.2
            · intro heq
              have hymem : y ∈ Finset.univ \ A := by simp [hyA]
              have := heq hymem
              simp at this
          exact ih _ hlt (insert y A) rfl y (Finset.mem_insert_self _ _)
        have hout : outflow q A = 0 := (h.conserve A hA hU).trans hi
        have he := flow_edge_le_outflow h hx
        have hnn := h.nonneg x A hx
        linarith

/-- A positive outgoing flow extends to a positive complete elimination path. -/
lemma exists_positive_path (h : IsFlow q m) (A : Finset X) (hpos : 0 < outflow q A) :
    ∃ l : List X, l.Nodup ∧ l.toFinset = A ∧
      ∀ x B, pathFlow l x B ≠ 0 → 0 < q x B := by
  induction hn : A.card using Nat.strong_induction_on generalizing A with
  | h n ih =>
      obtain ⟨y, hy, hqy⟩ := (Finset.sum_pos_iff_of_nonneg (fun x hx => h.nonneg x A hx)).mp hpos
      by_cases he : A.erase y = ∅
      · have hsing : ({y} : Finset X) = A := by
          have hAi : insert y (A.erase y) = A := Finset.insert_erase hy
          simpa [he] using hAi
        refine ⟨[y], by simp, by simpa using hsing, ?_⟩
        intro x B hp
        simp [pathFlow, unitEdge] at hp
        obtain ⟨hxy, hB⟩ := hp
        rw [hxy, hB, hsing]
        exact hqy
      · have hAe : (A.erase y).Nonempty := Finset.nonempty_iff_ne_empty.mpr he
        have hnotU : A.erase y ≠ Finset.univ := by
          intro heq
          have : y ∈ A.erase y := by rw [heq]; exact Finset.mem_univ y
          simp at this
        have hqin : q y A ≤ inflow q (A.erase y) := by
          have hymem : y ∈ Finset.univ \ A.erase y := by simp
          have hh := Finset.single_le_sum
            (fun z (hz : z ∈ Finset.univ \ A.erase y) =>
              h.nonneg z (insert z (A.erase y)) (Finset.mem_insert_self _ _)) hymem
          simpa [inflow, Finset.insert_erase hy] using hh
        have htailpos : 0 < outflow q (A.erase y) := by
          rw [h.conserve _ hAe hnotU]
          linarith
        obtain ⟨l, hln, hlA, hlpos⟩ :=
          ih _ (by rw [← hn]; exact Finset.card_erase_lt_of_mem hy) (A.erase y) htailpos rfl
        have hyn : y ∉ l := by
          have : y ∉ l.toFinset := by rw [hlA]; simp
          simpa using this
        refine ⟨y :: l, List.nodup_cons.mpr ⟨hyn, hln⟩, ?_, ?_⟩
        · simp [hlA, Finset.insert_erase hy]
        · intro x B hp
          by_cases hu : unitEdge y (y :: l).toFinset x B = 0
          · apply hlpos x B
            rw [pathFlow_cons, hu, zero_add] at hp
            exact hp
          · have heq : x = y ∧ B = (y :: l).toFinset := by
              simpa [unitEdge] using hu
            obtain ⟨rfl, rfl⟩ := heq
            simpa [hlA, Finset.insert_erase hy] using hqy

noncomputable def edgeSupport (q : X → Finset X → ℝ) : Finset (X × Finset X) :=
  Finset.univ.filter fun e => e.1 ∈ e.2 ∧ 0 < q e.1 e.2

@[simp] lemma mem_edgeSupport (q : X → Finset X → ℝ) (e : X × Finset X) :
    e ∈ edgeSupport q ↔ e.1 ∈ e.2 ∧ 0 < q e.1 e.2 := by
  simp [edgeSupport]

/-- Remove a positive complete unit path at its smallest edge weight. -/
lemma flow_subtract_path [Nonempty X] (h : IsFlow q m) (hm : 0 < m) :
    ∃ (l : List X) (δ : ℝ), l.Nodup ∧ l.toFinset = Finset.univ ∧ 0 < δ ∧
      IsFlow (fun x A => q x A - δ * pathFlow l x A) (m - δ) ∧
      (edgeSupport (fun x A => q x A - δ * pathFlow l x A)).card < (edgeSupport q).card := by
  classical
  obtain ⟨l, hln, hfull, hpos⟩ := exists_positive_path h Finset.univ (by rw [h.source]; exact hm)
  let E : Finset (X × Finset X) := Finset.univ.filter fun e => pathFlow l e.1 e.2 ≠ 0
  have hEmem : ∀ e, e ∈ E ↔ pathFlow l e.1 e.2 ≠ 0 := by intro e; simp [E]
  have hEn : E.Nonempty := by
    cases l with
    | nil =>
        have hu : (Finset.univ : Finset X) = ∅ := hfull.symm
        exact (Finset.univ_nonempty.ne_empty hu).elim
    | cons y l =>
        refine ⟨(y, (y :: l).toFinset), ?_⟩
        rw [hEmem]
        rw [pathFlow_head y l (List.nodup_cons.mp hln).1]
        norm_num
  obtain ⟨e, he, hmin⟩ := Finset.exists_min_image E (fun e => q e.1 e.2) hEn
  let δ := q e.1 e.2
  have hδ : 0 < δ := hpos e.1 e.2 ((hEmem e).mp he)
  have hpe : pathFlow l e.1 e.2 = 1 :=
    (pathFlow_eq_zero_or_one l hln e.1 e.2).resolve_left ((hEmem e).mp he)
  have hnn : ∀ x A, x ∈ A → 0 ≤ q x A - δ * pathFlow l x A := by
    intro x A hx
    rcases pathFlow_eq_zero_or_one l hln x A with hp | hp
    · simpa [hp] using h.nonneg x A hx
    · have hE : (x, A) ∈ E := (hEmem _).mpr (by rw [hp]; norm_num)
      have hle := hmin (x, A) hE
      simpa [hp, δ] using sub_nonneg.mpr hle
  have hr : IsFlow (fun x A => q x A - δ * pathFlow l x A) (m - δ) := by
    refine ⟨hnn, ?_, ?_⟩
    · rw [outflow_sub, outflow_mul, h.source, pathFlow_source l hln hfull, mul_one]
    · intro A hA hU
      rw [outflow_sub, inflow_sub, outflow_mul, inflow_mul, h.conserve A hA hU,
        pathFlow_conserve l hln hfull A hA hU]
  refine ⟨l, δ, hln, hfull, hδ, hr, ?_⟩
  apply Finset.card_lt_card
  have hsub : edgeSupport (fun x A => q x A - δ * pathFlow l x A) ⊆ edgeSupport q := by
    intro z hz
    obtain ⟨hzm, hzpos⟩ := (mem_edgeSupport _ z).mp hz
    apply (mem_edgeSupport _ z).mpr
    refine ⟨hzm, ?_⟩
    have hpnn := pathFlow_nonneg l z.1 z.2
    have hδnn : 0 ≤ δ := le_of_lt hδ
    nlinarith
  apply Finset.ssubset_iff_subset_ne.mpr
  refine ⟨hsub, ?_⟩
  intro heq
  have heqmem : e ∈ edgeSupport q := (mem_edgeSupport _ e).mpr
    ⟨pathFlow_nonzero_mem l ((hEmem e).mp he), hδ⟩
  rw [← heq] at heqmem
  have hfalse := ((mem_edgeSupport _ e).mp heqmem).2
  simp [δ, hpe] at hfalse

/-- Every nonnegative Boolean-lattice flow is a finite mixture of complete ranking paths.

This is proved by strong induction on the number of positive edges. Each step
subtracts the minimum edge weight of a positive complete path, annihilating
at least one edge. No flow decomposition theorem is assumed.
-/
theorem flow_decomposition [Nonempty X] (h : IsFlow q m) :
    ∃ μ : List X →₀ ℝ,
      (∀ l, 0 ≤ μ l) ∧
      (∀ l ∈ μ.support, l.Nodup ∧ l.toFinset = Finset.univ) ∧
      μ.sum (fun _ w => w) = m ∧
      (∀ x A, x ∈ A → μ.sum (fun l w => w * pathFlow l x A) = q x A) := by
  classical
  induction hn : (edgeSupport q).card using Nat.strong_induction_on generalizing q m with
  | h n ih =>
      by_cases hm0 : m = 0
      · subst m
        refine ⟨0, by simp, ?_, by simp, ?_⟩
        · intro l hl
          simp at hl
        · intro x A hx
          simpa using (flow_zero_of_source_zero h A x hx).symm
      · have hmnn : 0 ≤ m := by rw [← h.source]; exact flow_outflow_nonneg h _
        have hm : 0 < m := lt_of_le_of_ne hmnn (Ne.symm hm0)
        obtain ⟨l, δ, hln, hfull, hδ, hr, hlt⟩ := flow_subtract_path h hm
        obtain ⟨μ, hμnn, hμvalid, hμmass, hμedge⟩ :=
          ih _ (by simpa [hn] using hlt) hr rfl
        refine ⟨μ + Finsupp.single l δ, ?_, ?_, ?_, ?_⟩
        · intro k
          simp only [Finsupp.add_apply, Finsupp.single_apply]
          split_ifs <;> linarith [hμnn k]
        · intro k hk
          have hku := Finsupp.support_add hk
          rcases Finset.mem_union.mp hku with hkm | hkl
          · exact hμvalid k hkm
          · have hkl' := (Finsupp.mem_support_single k l δ).mp hkl
            rw [hkl'.1]
            exact ⟨hln, hfull⟩
        · rw [Finsupp.sum_add_index' (fun _ => rfl) (fun _ _ _ => rfl),
            Finsupp.sum_single_index rfl, hμmass]
          ring
        · intro x A hx
          rw [Finsupp.sum_add_index' (fun _ => zero_mul _) (fun _ _ _ => add_mul _ _ _),
            Finsupp.sum_single_index (zero_mul _), hμedge x A hx]
          ring

end Falmagne

/-! ## Conservation -/



namespace Falmagne
open Finset
open EconomicsNextProof
variable {X : Type*} [Fintype X] [DecidableEq X]

/-- The Block–Marschak transform of a finite choice rule. -/
noncomputable def blockMarschak (p : Finset X → X → ℝ) (x : X) (A : Finset X) : ℝ :=
  upperMobius (fun B => p B x) A

lemma blockMarschak_not_mem (p : Finset X → X → ℝ) (hp : IsChoiceRule p)
    (A : Finset X) (x : X) (hx : x ∉ A) :
    blockMarschak p x A = -blockMarschak p x (insert x A) := by
  classical
  let S := univ.filter (fun B : Finset X => A ⊆ B)
  let T := univ.filter (fun B : Finset X => insert x A ⊆ B)
  have hTS : T ⊆ S := by
    intro B hB
    simp only [T, S, mem_filter, mem_univ, true_and] at hB ⊢
    exact (subset_insert x A).trans hB
  have hrestrict : (∑ B ∈ S, (-1 : ℝ) ^ (B \ A).card * p B x) =
      ∑ B ∈ T, (-1 : ℝ) ^ (B \ A).card * p B x := by
    symm
    apply sum_subset hTS
    intro B hBS hBT
    have hxB : x ∉ B := by
      intro hxB
      apply hBT
      simp only [T, mem_filter, mem_univ, true_and]
      exact insert_subset hxB ((mem_filter.mp hBS).2)
    simp [hp.2.1 B x hxB]
  change (∑ B ∈ S, (-1 : ℝ) ^ (B \ A).card * p B x) =
    -(∑ B ∈ T, (-1 : ℝ) ^ (B \ insert x A).card * p B x)
  rw [hrestrict, ← sum_neg_distrib]
  apply sum_congr rfl
  intro B hBT
  have hxB : x ∈ B := (mem_filter.mp hBT).2 (mem_insert_self x A)
  have hd : B \ A = insert x (B \ insert x A) := by
    ext y
    simp only [mem_sdiff, mem_insert]
    constructor
    · intro hy
      by_cases hyx : y = x
      · exact Or.inl hyx
      · exact Or.inr ⟨hy.1, by simpa [hyx] using hy.2⟩
    · intro hy
      rcases hy with rfl | hy
      · exact ⟨hxB, hx⟩
      · exact ⟨hy.1, fun hyA => hy.2 (Or.inr hyA)⟩
  have hnot : x ∉ B \ insert x A := by simp
  rw [hd, card_insert_of_notMem hnot, pow_succ]
  ring

lemma blockMarschak_univ (p : Finset X → X → ℝ) (x : X) :
    blockMarschak p x univ = p univ x := by
  have hfilter : univ.filter (fun B : Finset X => univ ⊆ B) = {univ} := by
    ext B
    simp only [mem_filter, mem_univ, true_and, mem_singleton]
    exact ⟨fun h => Subset.antisymm (subset_univ B) h, fun h => by simp [h]⟩
  unfold blockMarschak upperMobius
  rw [hfilter]
  simp

lemma blockMarschak_source [Nonempty X] (p : Finset X → X → ℝ)
    (hp : IsChoiceRule p) : ∑ x : X, blockMarschak p x univ = 1 := by
  simp_rw [blockMarschak_univ]
  exact hp.2.2 univ univ_nonempty

/-- Normalization turns the total Möbius mass into a full-set point mass. -/
lemma blockMarschak_total (p : Finset X → X → ℝ) (hp : IsChoiceRule p)
    (A : Finset X) (hA : A.Nonempty) :
    ∑ x : X, blockMarschak p x A = if A = univ then 1 else 0 := by
  have hnorm (B : Finset X) (hAB : A ⊆ B) : (∑ x : X, p B x) = 1 := by
    calc
      (∑ x : X, p B x) = ∑ x ∈ B, p B x := by
        symm
        exact sum_subset (subset_univ B) (fun x _ hx => hp.2.1 B x hx)
      _ = 1 := hp.2.2 B (hA.mono hAB)
  unfold blockMarschak upperMobius
  rw [sum_comm]
  calc
    (∑ B ∈ univ.filter (fun B : Finset X => A ⊆ B),
        ∑ x : X, (-1 : ℝ) ^ (B \ A).card * p B x) =
      ∑ B ∈ univ.filter (fun B : Finset X => A ⊆ B),
        (-1 : ℝ) ^ (B \ A).card * 1 := by
      apply sum_congr rfl
      intro B hB
      rw [← mul_sum, hnorm B (mem_filter.mp hB).2]
    _ = if A = univ then 1 else 0 := upperMobius_const 1 A

lemma blockMarschak_conserve (p : Finset X → X → ℝ) (hp : IsChoiceRule p)
    (A : Finset X) (hA : A.Nonempty) (hproper : A ≠ univ) :
    (∑ x ∈ A, blockMarschak p x A) =
      ∑ x ∈ univ \ A, blockMarschak p x (insert x A) := by
  have htotal := blockMarschak_total p hp A hA
  rw [ite_eq_right hproper] at htotal
  have hoff : (∑ x ∈ univ \ A, blockMarschak p x A) =
      -(∑ x ∈ univ \ A, blockMarschak p x (insert x A)) := by
    rw [← sum_neg_distrib]
    apply sum_congr rfl
    intro x hx
    exact blockMarschak_not_mem p hp A x (mem_sdiff.mp hx).2
  have hsplit := sum_sdiff (subset_univ A) (f := fun x => blockMarschak p x A)
  rw [hoff, htotal] at hsplit
  linarith

/-- Nonnegative Block–Marschak coefficients form a unit Boolean-lattice flow. -/
theorem blockMarschak_isFlow [Nonempty X] (p : Finset X → X → ℝ)
    (hp : IsChoiceRule p)
    (hBM : ∀ x A, x ∈ A → 0 ≤ blockMarschak p x A) :
    IsFlow (blockMarschak p) 1 := by
  constructor
  · exact hBM
  · exact blockMarschak_source p hp
  · exact blockMarschak_conserve p hp

end Falmagne

/-! ## PathChoice -/



namespace Falmagne
variable {X : Type*} [Fintype X] [DecidableEq X]
variable {l : List X} {x y : X} {A : Finset X}

lemma lowerContour_cons_self (h : x ∉ l) :
    lowerContour (x :: l) x = (x :: l).toFinset := by
  ext y
  simp [lowerContour]

lemma lowerContour_cons_of_ne (hxy : x ≠ y) (hyn : y ∉ l) :
    lowerContour (y :: l) x = lowerContour l x := by
  ext z
  by_cases hz : z = y
  · subst z
    simp [lowerContour, hyn, List.idxOf_cons_ne l hxy.symm]
  · simp [lowerContour, hz, List.idxOf_cons_ne l hxy.symm, List.idxOf_cons_ne l (Ne.symm hz)]

lemma pathFlow_eq_lowerContour (hl : l.Nodup) (hx : x ∈ l) :
    pathFlow l x A = if A = lowerContour l x then 1 else 0 := by
  induction l with
  | nil => simp at hx
  | cons y l ih =>
      obtain ⟨hyn, hln⟩ := List.nodup_cons.mp hl
      by_cases hxy : x = y
      · subst x
        rw [pathFlow_cons, pathFlow_zero_of_not_mem l hyn, add_zero,
          lowerContour_cons_self hyn]
        simp [unitEdge]
      · have hx' : x ∈ l := (List.mem_cons.mp hx).resolve_left hxy
        rw [pathFlow_cons, lowerContour_cons_of_ne hxy hyn, ih hln hx']
        simp [unitEdge, hxy]

lemma pathFlow_eq_rankingEdge (hl : IsRanking l) :
    pathFlow l x A = rankingEdge l x A := by
  rw [pathFlow_eq_lowerContour hl.1 (ranking_mem hl x)]
  unfold rankingEdge
  by_cases hA : A = lowerContour l x
  · subst A
    simp [self_mem_lowerContour hl x]
  · simp [hA]

end Falmagne

/-! ## ChoiceMobius -/



namespace Falmagne
open EconomicsNextProof
variable {X : Type*} [Fintype X] [DecidableEq X]
variable {l : List X} {A : Finset X} {x : X}

lemma upperSum_rankingEdge (hl : IsRanking l) (x : X) (A : Finset X) (hx : x ∈ A) :
    upperSum (rankingEdge l x) A = rankingChoice l A x := by
  by_cases hA : A ⊆ lowerContour l x
  · unfold upperSum
    rw [Finset.sum_eq_single (lowerContour l x)]
    · simp [rankingEdge, self_mem_lowerContour hl x, rankingChoice, hA, hx]
    · intro B hB hne
      simp [rankingEdge, hne]
    · intro hn
      exact (hn (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hA⟩)).elim
  · have hz : upperSum (rankingEdge l x) A = 0 := by
      unfold upperSum
      apply Finset.sum_eq_zero
      intro B hB
      have hne : B ≠ lowerContour l x := by
        intro h
        exact hA (h ▸ (Finset.mem_filter.mp hB).2)
      simp [rankingEdge, hne]
    rw [hz]
    simp [rankingChoice, hA]

lemma upperSum_lawFlow (w : RankingLaw X) (hw : ∀ l ∈ w.support, IsRanking l)
    (x : X) (A : Finset X) (hx : x ∈ A) :
    upperSum (lawFlow w x) A = w.sum (fun l a => a * rankingChoice l A x) := by
  unfold upperSum lawFlow Finsupp.sum
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro l hl
  rw [← Finset.mul_sum]
  congr 1
  exact upperSum_rankingEdge (hw l hl) x A hx

/-- The Möbius coefficient equals the probability of the exact lower contour. -/
theorem mobius_eq_lawFlow {w : RankingLaw X} {p : Finset X → X → ℝ}
    (hw : ∀ l ∈ w.support, IsRanking l) (hp : Represents w p) (x : X) (A : Finset X)
    (hx : x ∈ A) :
    upperMobius (fun B => p B x) A = lawFlow w x A := by
  calc
    _ = upperMobius (upperSum (lawFlow w x)) A := by
      unfold upperMobius
      apply Finset.sum_congr rfl
      intro B hB
      have hAB : A ⊆ B := (Finset.mem_filter.mp hB).2
      rw [upperSum_lawFlow w hw x B (hAB hx)]
      change _ * p B x = _
      rw [hp B x]
    _ = lawFlow w x A := congrFun (upperMobius_upperSum (lawFlow w x)) A

/-- Every random-ranking choice rule satisfies all Block–Marschak inequalities. -/
theorem blockMarschak_necessary {w : RankingLaw X} {p : Finset X → X → ℝ}
    (hw : IsRankingLaw w) (hp : Represents w p) :
    ∀ x A, x ∈ A → 0 ≤ upperMobius (fun B => p B x) A := by
  intro x A hx
  rw [mobius_eq_lawFlow hw.2.1 hp x A hx]
  exact lawFlow_nonneg hw.1 x A

end Falmagne

/-! ## Falmagne -/


/-!
# Falmagne–Block–Marschak random-utility characterization

The alternative type is any finite nonempty type. A single probability distribution
on complete strict rankings reproduces every nonempty-menu choice exactly if all
Block–Marschak coefficients are nonnegative. The sufficiency proof constructs the
ranking law from the nonnegative Boolean-lattice flow. No decomposition hypothesis
is part of the economic statement.

Primary references:
* Falmagne (1978), A representation theorem for finite random scale systems.
* Fiorini (2004), A short proof of a theorem of Falmagne.
* Doignon and Saito (2023), Adjacencies on random ordering polytopes and flow polytopes.
-/

namespace Falmagne
open EconomicsNextProof
variable {X : Type*} [Fintype X] [DecidableEq X] [Nonempty X]

/-- The exact observed probabilities satisfy all Block–Marschak inequalities. -/
def BlockMarschakNonnegative (p : Finset X → X → ℝ) : Prop :=
  ∀ x A, x ∈ A → 0 ≤ blockMarschak p x A

/-- Stochastic rationalizability by a single menu-independent strict-ranking law. -/
def RandomUtilityRepresentable (p : Finset X → X → ℝ) : Prop :=
  ∃ w : RankingLaw X, IsRankingLaw w ∧ Represents w p

lemma randomUtility_necessary {p : Finset X → X → ℝ}
    (h : RandomUtilityRepresentable p) : BlockMarschakNonnegative p := by
  obtain ⟨w, hw, hp⟩ := h
  exact blockMarschak_necessary hw hp

/-- Construct a common ranking law from the nonnegative Block–Marschak flow. -/
lemma randomUtility_sufficient {p : Finset X → X → ℝ}
    (hp : IsChoiceRule p) (hBM : BlockMarschakNonnegative p) :
    RandomUtilityRepresentable p := by
  obtain ⟨w, hnonneg, hrank, hmass, hflow⟩ :=
    flow_decomposition (blockMarschak_isFlow p hp hBM)
  refine ⟨w, ⟨hnonneg, hrank, hmass⟩, ?_⟩
  intro A x
  by_cases hx : x ∈ A
  · have hwflow : ∀ B, x ∈ B → lawFlow w x B = blockMarschak p x B := by
      intro B hxB
      calc
        lawFlow w x B = w.sum (fun l a => a * pathFlow l x B) := by
          unfold lawFlow Finsupp.sum
          apply Finset.sum_congr rfl
          intro l hl
          change w l * rankingEdge l x B = w l * pathFlow l x B
          rw [pathFlow_eq_rankingEdge (hrank l hl)]
        _ = blockMarschak p x B := hflow x B hxB
    calc
      p A x = upperSum (blockMarschak p x) A := by
        exact (congrFun (upperSum_upperMobius (fun B => p B x)) A).symm
      _ = upperSum (lawFlow w x) A := by
        unfold upperSum
        apply Finset.sum_congr rfl
        intro B hB
        exact (hwflow B ((Finset.mem_filter.mp hB).2 hx)).symm
      _ = w.sum (fun l a => a * rankingChoice l A x) :=
        upperSum_lawFlow w hrank x A hx
  · rw [hp.2.1 A x hx]
    simp [rankingChoice, hx]

/-- Full Falmagne–Block–Marschak equivalence on an arbitrary finite alternative set. -/
theorem falmagne_blockMarschak {p : Finset X → X → ℝ} (hp : IsChoiceRule p) :
    RandomUtilityRepresentable p ↔ BlockMarschakNonnegative p :=
  ⟨randomUtility_necessary, randomUtility_sufficient hp⟩

end Falmagne
